# Generated by Django 5.2.4 on 2025-08-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('family', 'Family'), ('caregiver', 'Caregiver'), ('admin', 'Admin')], default='family', max_length=20),
        ),
    ]
