# Generated by Django 5.2.4 on 2025-08-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='charge_per_hour',
        ),
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='qualification',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='specialization',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
